### ISSUE TITLE
Apply message filters

### ISSUE THREAD

**Issue by Georacer** [Georacer/ardupilog#16]
Hunter,

Do you think it would be of any merit to filter the parsed messages before storing them, against a provided message list?

I think the complexity to do it during parsing would be substantial, whereas a simple array deletion post-parsing is trivial.
Plus, I don't expect any time savings if we choose to do it the 1st way.

**Comment by hunt0r** [comment]
I don't think I understand... what do you mean by "filtering" the parsed messages?

**Comment by Georacer** [comment]
In case someone is interest only in e.g. RCOU, RPM, ATT messages, only these would be included in the output log.

Superficial, really, it's just that other similar analyzers provide that functionality.

**Comment by hunt0r** [comment]
Oh yes, okay. I'll keep this in mind. It would make good sense to implement this with a move to a batch-style processing of LogMsgGroups, as mentioned in issue #9

**Comment by Georacer** [comment]
Closed by #26
