### ISSUE TITLE
What's the difference between the "length" of a message as provided by FMT, vs the sum of the lengths of the field identifiers? (BQNnz, for example)

### ISSUE THREAD

**Issue by Georacer** [Georacer/ardupilog#24]
As extracted from code comments.

**Comment by Georacer** [comment]
@hunt0r 
Do you think these may differ? Do you feel like we should check this for all messages?

**Comment by hunt0r** [comment]
Well... I hope they don't.

Looking in LogStructure.h, it seems that the length provided by FMT is the returned value for sizeof() on the struct. Inside the struct definition, the field identifier string (e.g. "BQNnz") is hand-coded to correspond to the data in the struct.

So if they ever differ, I think that's a mistake. This seems like redundant information (which is to-be-avoided, in my opinion) but probably not worth our time.

I think we should assume they will always agree. Is that fine with you?

**Comment by Georacer** [comment]
Let's leave this open and at some point one of us might code an assertion function for that.

**Comment by Georacer** [comment]
This is tested by #31
