### ISSUE TITLE
Slicing functionality

### ISSUE THREAD

**Issue by Georacer** [Georacer/ardupilog#35]
It is desirable that functionality is implemented for:

- Cropping an Ardupilog object to a smaller time window
- Cropping one or more windows out of the log and keeping the rest

Arguments for cropping could be time or line indexed. For example:

- [x] getSlice([50 5000], ‘LineNo’)
- [x] getSlice([0 5.37],’TimeUS’)
- [x] getSlice([0 105.1],’TimeS’)
- [ ] getSlice([t1 t2],’TimeUTC’)
- [ ] double value = getSlice(5.4,’TimeS’) % For interpolation
- [ ] getSlice(times,’type’,’endpoints’,’format’,’UTC’)
- [ ] double interps = getSlice(times,’type’,’interp’,’format’,’TimeS’)

**Comment by hunt0r** [comment]
Began addressing in #47

**Comment by Georacer** [comment]
'TimeUS' was dropped, since not all messages have this field and also such fine-grained resolution is not needed.

**Comment by hunt0r** [comment]
At present, I use slicing often, and it works pretty well. Should we close this Issue?

**Comment by Georacer** [comment]
Yeah, I think it serves its purpose well. Go ahead!
