### ISSUE TITLE
Find a way to count the number of message lines efficiently

### ISSUE THREAD

**Issue by Georacer** [Georacer/ardupilog#6]
This will be primarily used to display a progress bar.

**Comment by Georacer** [comment]
I couldn't think of a quick matlab way to do it.
Tried finding a Linux way to do it and the closest I get is
`od -xAx 66.BIN | tr -d '\n' | grep -o "a3 \?95" | wc -l`
But I'm sure the result isn't correct.

**Comment by hunt0r** [comment]
Solved by #7
