### ISSUE TITLE
bootTimeUTC and dateNumUTC appear incorrect

### ISSUE THREAD

**Issue by samuelctabor** [Georacer/ardupilog#87]
From recent logs I am getting incorrect datenums.

E.g.

```
>> log.bootTimeUTC

ans =

1980-01-05 23:59:50
```

```
>> datestr(max(log.GPS.DatenumUTC))

ans =

06-Jan-1980 07:30:00
```

**Comment by samuelctabor** [comment]
Actually it is correct on master, I was using a cached .mat saved from a previous version output

**Comment by Georacer** [comment]
Nice to hear. Those leap seconds are a pain.
