### ISSUE TITLE
Error running the code

### ISSUE THREAD

**Issue by isso11** [Georacer/ardupilog#89]
Hi,

When I run the code and select a .BIN log  file, I get this error:

```
'RSSI' is already defined as a property.

Error in Ardupilog/createLogMsgGroups (line 322)
                    addprop(obj, newName);
```

I tried to upload the .BIN file on Flight Log Review website and it works fine. So I assume the file itself is okay.

Any help would be appreciated!

**Comment by Georacer** [comment]
Hello and thank you for the ticket.

There is a very recent PR that might fix this new issue: https://github.com/Georacer/ardupilog/pull/88

I haven't merged it yet, I will do it within the next week. In the meantime, you might be able to use that branch to open your log, if you know how to do it.

**Comment by isso11** [comment]
Thank you. It worked. @Georacer
